SET foreign_key_checks = 0;
DELETE FROM Role;
DELETE FROM User;
DELETE FROM Eggs;
delete  from zipCodeWeather;
TRUNCATE TABLE Role;
TRUNCATE TABLE EggCheckerTest.User;
TRUNCATE TABLE Eggs;
TRUNCATE TABLE zipCodeWeather;
SET foreign_key_checks = 1;