INSERT INTO EggCheckerTest.User (userName, userPass) VALUES ('UnitTester0', 'supersecret0');
INSERT INTO EggCheckerTest.User (userName, userPass) VALUES ('UnitTester1', 'supersecret1');
INSERT INTO EggCheckerTest.User (userName, userPass) VALUES ('UnitTester2', 'supersecret2');
INSERT INTO EggCheckerTest.User (userName, userPass) VALUES ('UnitTester3', 'supersecret3');
INSERT INTO EggCheckerTest.User (userName, userPass) VALUES ('UnitTesterAdmin', 'supersecret4');
INSERT INTO EggCheckerTest.Role (userName, name) VALUES ('UnitTester0', 'user');
INSERT INTO EggCheckerTest.Role (userName, name) VALUES ('UnitTester1', 'user');
INSERT INTO EggCheckerTest.Role (userName, name) VALUES ('UnitTester2', 'user');
INSERT INTO EggCheckerTest.Role (userName, name) VALUES ('UnitTester3', 'user');
INSERT INTO EggCheckerTest.Role (userName, name) VALUES ('UnitTesterAdmin', 'admin');
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('duck', 1, '12/30/1000', 1);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('chicken', 1, '1/1/1000', 2);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('duck', 2, '1/30/1000', 1);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('chicken', 2, '1/10/1000', 2);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('duck', 3, '1/30/1000', 1);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('chicken', 3, '1/10/1000', 2);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('duck', 4, '1/30/1000', 1);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('chicken', 4, '1/10/1000', 2);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('duck', 5, '1/30/1000', 2);
INSERT INTO EggCheckerTest.Eggs (type, userId, collectedDate, perUserId) VALUES ('chicken', 5, '1/10/1000', 1);